import type { IBackend } from './backend';

export const st = {
  rootHandle: null as any,
  backend: null as IBackend | null,
  vaultName: null as string | null,
  allFilesMeta: [] as any[],
  wikilinksFrom: new Map<string, Set<string>>(),
  mdlinksFrom: new Map<string, Set<string>>(),
  fileBaseIndex: new Map<string, string[]>(),
  fileContentCache: new Map<string, string>(),
  linkIndexBuilt: false,
  currentDir: '',
  currentFile: null as string | null,
  autoFocusFirstOnLoad: false,
  isEditing: false,
  isInlineRenaming: false,
  isDirty: false,
  pendingHtmlContent: null as string | null,
  _loadFileSeq: 0,
  _loadDirSeq: 0,
  _linkIndexRunning: false,
  isSaving: false,
  _currentFileMtime: 0 as number,
  autosaveTimer: null as any,
  cmEditor: null as any,
  injectedPluginEls: [] as HTMLElement[],
  sortOrder: 'desc',
  sortBy: 'mtime',
  settingsActive: false,
  settingsPrevBreadcrumb: '',
  savedHandleForResume: null as any,
  dissolveTimer: null as any,
  charTimers: [] as any[],
  isDissolved: false,
  sidebarOpenWidth: 280,
  _swipeStartX: 0,
  _swipeStartY: 0,
  welcomeSearchInput: null as HTMLInputElement | null,
};
